apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
  labels:
    control-plane: controller-manager
spec:
  selector:
    matchLabels:
      control-plane: controller-manager
  replicas: 1
  template:
    metadata:
      labels:
        control-plane: controller-manager
    spec:
      containers:
      - command:
        - /manager
        args:
        - --enable-leader-election
        image: controller:latest
        imagePullPolicy: Always
        name: manager
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          limits:
            cpu: 1
            memory: 4Gi
          requests:
            cpu: 100m
            memory: 2Gi
        volumeMounts:
            - mountPath: /opt/kafka/external-configuration/rds-client-ca
              name: rds-client-ca
        ports:
        - name: metrics
          containerPort: 8080
          protocol: TCP
      volumes:
        - name: rds-client-ca
          secret:
            secretName: rds-client-ca
            defaultMode: 420
            optional: true
      serviceAccountName: controller-manager
      terminationGracePeriodSeconds: 10
