apiVersion: v1
data:
  db.host: YWR2aXNvci1kYg==
  db.name: aW5zaWdodHM=
  db.password: aW5zaWdodHM=
  db.port: NTQzMw==
  db.user: aW5zaWdodHM=
kind: Secret
metadata:
  name: advisor-db
type: Opaque
