apiVersion: v1
data:
  db.host: YWR2aXNvci1kYg==
  db.name: aW5zaWdodHNhcGk=
  db.password: aW5zaWdodHNhcGk=
  db.port: NTQzMg==
  db.user: aW5zaWdodHNhcGk=
kind: Secret
metadata:
  name: advisor-db
type: Opaque