apiVersion: kafka.strimzi.io/v1beta1
kind: Kafka
metadata:
  name: my-cluster
spec:
  kafka:
    replicas: 1
    listeners:
      plain: {}
      tls: {}
      external:
        type: nodeport
        tls: false
        overrides:
          brokers:
          - broker: 0
            advertisedHost: "192.168.130.11"
    storage:
      type: jbod
      volumes:
      - id: 0
        type: persistent-claim
        size: 100Gi
        deleteClaim: false
    config:
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
    # workaround for https://github.com/strimzi/strimzi-kafka-operator/issues/912
    template:
      pod:
        securityContext: {}
  zookeeper:
    replicas: 1
    storage:
      type: persistent-claim
      size: 100Gi
      deleteClaim: false
    # workaround for https://github.com/strimzi/strimzi-kafka-operator/issues/912
    template:
      pod:
        securityContext: {}
  entityOperator:
    topicOperator: {}
    userOperator: {}
