apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: my-cluster
spec:
  kafka:
    replicas: 1
    authorization:
      type: simple
      superUsers:
        - ANONYMOUS
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: auth
        port: 9093
        type: internal
        tls: false
        authentication:
          type: scram-sha-512
      - name: nodeport
        type: nodeport
        port: 9094
        tls: false
        configuration:
          brokers:
          - broker: 0
            advertisedHost: "192.168.130.11"
    storage:
      type: jbod
      volumes:
      - id: 0
        type: persistent-claim
        size: 5Gi
        deleteClaim: false
    config:
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
    # workaround for https://github.com/strimzi/strimzi-kafka-operator/issues/912
    template:
      pod:
        securityContext: {}
  zookeeper:
    replicas: 1
    storage:
      type: persistent-claim
      size: 1Gi
      deleteClaim: false
    # workaround for https://github.com/strimzi/strimzi-kafka-operator/issues/912
    template:
      pod:
        securityContext: {}
  entityOperator:
    topicOperator: {}
    userOperator: {}
