apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnect
metadata:
  name: xjoin-kafka-connect-strimzi
  annotations:
  # use-connector-resources configures this KafkaConnect
  # to use KafkaConnector resources to avoid
  # needing to call the Connect REST API directly
    strimzi.io/use-connector-resources: "true"
spec:
  image: quay.io/cloudservices/insights-kafka-connect:latest
  version: 2.6.2
  replicas: 1
  bootstrapServers: my-cluster-kafka-bootstrap:9093
  externalConfiguration:
    env:
      - name: ADVISOR_DB_NAME
        valueFrom:
          secretKeyRef:
            key: db.name
            name: advisor-db
      - name: ADVISOR_DB_HOSTNAME
        valueFrom:
          secretKeyRef:
            key: db.host
            name: advisor-db
      - name: ADVISOR_DB_USERNAME
        valueFrom:
          secretKeyRef:
            key: db.user
            name: advisor-db
      - name: ADVISOR_DB_PASSWORD
        valueFrom:
          secretKeyRef:
            key: db.password
            name: advisor-db
      - name: ADVISOR_DB_PORT
        valueFrom:
          secretKeyRef:
            key: db.port
            name: advisor-db
  config:
    config.providers: env
    config.providers.env.class: com.redhat.insights.kafka.config.providers.EnvironmentConfigProvider
    group.id: cyndi-connect
    offset.storage.topic: cyndi-connect-offsets
    offset.storage.replication.factor: 1
    config.storage.topic: cyndi-connect-configs
    config.storage.replication.factor: 1
    status.storage.topic: cyndi-connect-status
    status.storage.replication.factor: 1
  authentication:
    type: scram-sha-512
    username: kafka-cyndi
    passwordSecret:
      secretName: kafka-cyndi
      password: password
  template:
    pod:
      securityContext: {}
