apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnect
metadata:
  name: xjoin-kafka-connect-strimzi
  annotations:
  # use-connector-resources configures this KafkaConnect
  # to use KafkaConnector resources to avoid
  # needing to call the Connect REST API directly
    strimzi.io/use-connector-resources: "true"
spec:
  image: quay.io/cloudservices/xjoin-kafka-connect-strimzi:latest
  version: 2.6.2
  replicas: 1
  bootstrapServers: my-cluster-kafka-bootstrap:9093
  config:
    group.id: cyndi-connect
    offset.storage.topic: cyndi-connect-offsets
    offset.storage.replication.factor: 1
    config.storage.topic: cyndi-connect-configs
    config.storage.replication.factor: 1
    status.storage.topic: cyndi-connect-status
    status.storage.replication.factor: 1
  authentication:
    type: scram-sha-512
    username: kafka-cyndi
    passwordSecret:
      secretName: kafka-cyndi
      password: password
  template:
    pod:
      securityContext: {}
