{
 "title": "Cyndi",
 "tags": [
  "platform-health",
  "cyndi"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   { "name": "datasource_awskafka", "label": "Datasource - AWS Kafka", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "SLO", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Consumer lag by application",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "min(\nsum(\nlabel_replace(\naws_kafka_sum_offset_lag_sum{topic=\"platform.inventory.events\", consumer_group=~\"connect-cyndi-.*\"},\n\"cyndi_application\", \"$1\", \"consumer_group\", \"connect-cyndi-(.*)-([0-9]+)-.*\")\n) by (consumer_group, cyndi_application)\n\n) by (cyndi_application)",
     "legendFormat": "{{cyndi_application}}"
    }
   ]
  },
  {
   "title": "Inconsistency ratio by application",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(cyndi_inconsistency_ratio) by (app)",
     "legendFormat": "{{app}}"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "label_replace(\nmax(quantile_over_time(0.95, cyndi:consumer_group_lag:min_per_app[$__range])) by (cyndi_application)\n, \"app\", \"$1\", \"cyndi_application\", \"(.+)\"\n)",
     "legendFormat": "Latency (95th quantile)"
    },
    {
     "expr": "1 - max(quantile_over_time(0.95, cyndi_inconsistency_ratio[$__range])) by (app)",
     "legendFormat": "Consistency (95th quantile)"
    }
   ]
  },
  {
   "title": "Pipelines",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "Incoming Message Rate",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(rate(aws_kafka_sum_offset_lag_sum{topic=\"platform.inventory.events\"}[1m]))",
       "legendFormat": "platform.inventory.events"
      }
     ]
    },
    {
     "title": "Inconsistency (absolute) by application",
     "type": "graph",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 13 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(cyndi_inconsistency_total) by (app)",
       "legendFormat": "{{app}}"
      }
     ]
    },
    {
     "title": "Host count by application",
     "type": "graph",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(cyndi_hosts_total) by (app)",
       "legendFormat": "{{app}}"
      }
     ]
    },
    {
     "title": "Cyndi connectors",
     "type": "table-old",
     "gridPos": { "h": 18, "w": 12, "x": 12, "y": 24 },
     "targets": [
      {
       "expr": "sum(\nlabel_replace(\naws_kafka_sum_offset_lag_sum{topic=\"platform.inventory.events\", consumer_group=~\"connect-cyndi-.*\"},\n\"connector\", \"$1\", \"consumer_group\", \"connect-(cyndi-.*)\")\n) by (connector)",
       "legendFormat": "{{connector}}"
      },
      {
       "expr": "sum(kafka_connect_worker_connector_running_task_count{connector=~\"cyndi-.*\"}) by (connector) OR sum (kafka_connect_connect_worker_metrics_connector_running_task_count{connector=~\"syndication-sink-.*\"}) by (connector)",
       "legendFormat": "{{connector}}"
      },
      {
       "expr": "sum(kafka_connect_worker_connector_paused_task_count{connector=~\"cyndi-.*\"}) by (connector) OR sum (kafka_connect_connect_worker_metrics_connector_paused_task_count{connector=~\"syndication-sink-.*\"}) by (connector)",
       "legendFormat": "{{connector}}"
      },
      {
       "expr": "sum(kafka_connect_worker_connector_paused_task_count{connector=~\"cyndi-.*\"}) by (connector) OR  sum (kafka_connect_connect_worker_metrics_connector_failed_task_count{connector=~\"syndication-sink-.*\"}) by (connector)",
       "legendFormat": "{{connector}}"
      }
     ]
    },
    {
     "title": "Validation failure rate [5min]",
     "type": "graph",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 31 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(cyndi_validation_failed_total[5m])) by (app)",
       "legendFormat": "{{app}}"
      }
     ]
    },
    {
     "title": "Refresh rate [5min]",
     "type": "graph",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 42 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(cyndi_refresh_total[5m])) by (app)",
       "legendFormat": "{{app}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Operator",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "Reconciliation time (controller)",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
     "targets": [
      {
       "expr": "sum(rate(controller_runtime_reconcile_time_seconds_bucket{controller=\"cyndi-controller\"}[1m])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Reconciliation rate [1m]",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(controller_runtime_reconcile_total{controller=~\"cyndi.*\"}[1m])) by (controller)",
       "legendFormat": "{{controller}}"
      }
     ]
    },
    {
     "title": "Reconciliation time (validator)",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
     "targets": [
      {
       "expr": "sum(rate(controller_runtime_reconcile_time_seconds_bucket{controller=\"cyndi-validation\"}[1m])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    }
   ]
  }
 ]
}