apiVersion: v1
kind: Template
metadata:
  name: cyndi-operator-config

parameters:
- name: RECONCILE_INTERVAL
  value: "120"
- name: VALIDATION_INTERVAL
  value: "1800"
- name: VALIDATION_INTERVAL_INIT
  value: "60"
- name: VALIDATION_PERCENTAGE_THRESHOLD
  value: "5"
- name: VALIDATION_ATTEMPTS_THRESHOLD
  value: "3"
- name: VALIDATION_ATTEMPTS_THRESHOLD_INIT
  value: "15"
- name: CONNECT_CLUSTER
  value: "xjoin-kafka-connect-strimzi"

objects:
- apiVersion: v1
  kind: ConfigMap
  metadata:
    name: cyndi
  data:
    standard.interval: ${RECONCILE_INTERVAL}
    validation.interval: ${VALIDATION_INTERVAL}
    validation.attempts.threshold: ${VALIDATION_ATTEMPTS_THRESHOLD}
    validation.percentage.threshold: ${VALIDATION_PERCENTAGE_THRESHOLD}
    init.validation.interval: ${VALIDATION_INTERVAL_INIT}
    init.validation.attempts.threshold: ${VALIDATION_ATTEMPTS_THRESHOLD_INIT}
    init.validation.percentage.threshold: ${VALIDATION_PERCENTAGE_THRESHOLD}
    connect.cluster: ${CONNECT_CLUSTER}
