apiVersion: v1
kind: Template
metadata:
  name: kafka-user

parameters:
- name: GROUP_ID
  value: cyndi
- name: CONNECTOR_GROUP_PREFIX
  value: connect-cyndi
- name: KAFKA_CLUSTER
  value: platform-mq

objects:
- apiVersion: kafka.strimzi.io/v1beta2
  kind: KafkaUser
  metadata:
    name: kafka-cyndi
    labels:
      strimzi.io/cluster: ${KAFKA_CLUSTER}
  spec:
    authentication:
      type: scram-sha-512
    authorization:
      acls:
      # topics
      - resource:
          name: 'platform.inventory.events'
          patternType: literal
          type: topic
        operation: Read

      - resource:
          name: 'platform.cyndi.dlq'
          patternType: literal
          type: topic
        operation: All

      # connect offset, storage and config topics
      - resource:
          name: 'cyndi-connect'
          patternType: prefix
          type: topic
        operation: All

      # connect cluster consumer group
      - resource:
          name: ${GROUP_ID}
          patternType: literal
          type: group
        operation: All
      # connector consumer groups
      - resource:
          name: ${CONNECTOR_GROUP_PREFIX}
          patternType: prefix
          type: group
        operation: All
      type: simple
