apiVersion: apps/v1
kind: Deployment
metadata:
  name: cyndi-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: cyndi-operator
  template:
    metadata:
      labels:
        name: cyndi-operator
    spec:
      serviceAccountName: cyndi-operator
      containers:
        - name: cyndi-operator
          # Replace this with the built image name
          image: image-registry.openshift-image-registry.svc:5000/default/cyndi-operator:v0.0.1
          command:
          - cyndi-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "cyndi-operator"
