apiVersion: v1
data:
  standard.interval: '120'
  validation.interval: '60'
  validation.attempts.threshold: '5'
  validation.percentage.threshold: '5'
  init.validation.interval: '10'
  init.validation.attempts.threshold: '10'
  init.validation.percentage.threshold: '5'
  connect.cluster: 'my-connect-cluster'
  connector.tasks.max: '1'
kind: ConfigMap
metadata:
  name: cyndi
