apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: cyndipipelines.cyndi.cloud.redhat.com
spec:
  group: cyndi.cloud.redhat.com
  names:
    kind: CyndiPipeline
    listKind: CyndiPipelineList
    plural: cyndipipelines
    singular: cyndipipeline
  scope: Namespaced
  versions:
  - name: v1beta1
    schema:
      openAPIV3Schema:
        description: CyndiPipeline is the Schema for the cyndipipelines API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: CyndiPipelineSpec defines the desired state of CyndiPipeline
            type: object
          status:
            description: CyndiPipelineStatus defines the observed state of CyndiPipeline
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
